### ISSUE TITLE
Install Error Mac

### ISSUE THREAD

**Issue by EdwardKepler** [CommonGarden/CommonGarden-IoT#450] opened 2018-03-03 14:10 UTC
W20180303-08:07:52.579(-6)? (STDERR) /Users/edwardkepler/.meteor/packages/meteor-tool/.1.6.1.194wnfx.1kqp++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20180303-08:07:52.579(-6)? (STDERR) 						throw(ex);
W20180303-08:07:52.580(-6)? (STDERR) 						^
W20180303-08:07:52.580(-6)? (STDERR) 
W20180303-08:07:52.580(-6)? (STDERR) Error: Cannot find module 'faye-websocket'
W20180303-08:07:52.580(-6)? (STDERR)     at makeMissingError (packages/modules-runtime.js:231:12)
W20180303-08:07:52.581(-6)? (STDERR)     at require (packages/modules-runtime.js:241:19)
W20180303-08:07:52.581(-6)? (STDERR)     at ddp-client.js (packages/modules.js:2321:17)
W20180303-08:07:52.581(-6)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)
W20180303-08:07:52.581(-6)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180303-08:07:52.582(-6)? (STDERR)     at Thing.js (packages/modules.js:367:19)
W20180303-08:07:52.582(-6)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)
W20180303-08:07:52.582(-6)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180303-08:07:52.584(-6)? (STDERR)     at Grow.js (Grow-IoT/packages/Grow.js/lib/Grow.js:1:15)
W20180303-08:07:52.584(-6)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)
W20180303-08:07:52.584(-6)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180303-08:07:52.584(-6)? (STDERR)     at /Users/edwardkepler/Grow-IoT/.meteor/local/build/programs/server/app/app.js:7438:1
W20180303-08:07:52.585(-6)? (STDERR)     at /Users/edwardkepler/Grow-IoT/.meteor/local/build/programs/server/boot.js:411:36
W20180303-08:07:52.585(-6)? (STDERR)     at Array.forEach (<anonymous>)
W20180303-08:07:52.585(-6)? (STDERR)     at /Users/edwardkepler/Grow-IoT/.meteor/local/build/programs/server/boot.js:220:19
W20180303-08:07:52.586(-6)? (STDERR)     at /Users/edwardkepler/Grow-IoT/.meteor/local/build/programs/server/boot.js:471:5
W20180303-08:07:52.586(-6)? (STDERR)     at Function.run (/Users/edwardkepler/Grow-IoT/.meteor/local/build/programs/server/profile.js:510:12)
W20180303-08:07:52.586(-6)? (STDERR)     at /Users/edwardkepler/Grow-IoT/.meteor/local/build/programs/server/boot.js:470:11

**Comment by JakeHartnell** [comment] 2018-06-24 17:38
There are a few ways to potentially solve this if it's still an issue.

1. Since the error is `Error: Cannot find module 'faye-websocket'` you could simply install faye-websocket by running `npm install faye-websocker`.
2. If that doesn't work, delete the `node_modules` folder and reinstall the dependencies with `meteor npm install` or `yarn` or `npm install`

Hope that helps if it's still an issue. Since I can't reproduce this I will close this issue for now.

**Closed as completed by JakeHartnell** 2018-06-24 17:38 UTC
